providers:
  default:
    base_url: https://chat.openai.com/v1
    api_type: openai
    api_key: !env OPENAI_API_KEY
models:
  default:
    id: gpt-5
  whisper:
    id: whisper-1
stt:
  default:
    model: whisper
    language: ru
sessions_storages:
  default:
    type: filesystem
memory:
  driver:
    type: filesystem
    workspace: !env [MICROCLAW_WORKSPACE, /data/workspace]
toolkits:
  email:
    path: microclaw.toolkits.email.EmailToolKit
    args:
      smtp_host: smtp.gmail.com
      smtp_port: 465
      smtp_tls_mode: ssl
      imap_host: imap.gmail.com
      imap_port: 993
      imap_tls_mode: ssl
      username: !env EMAIL_USERNAME
      password: !env EMAIL_PASSWORD
  tasks:
    path: microclaw.toolkits.tasks.TasksToolKit
    args:
      url: https://cloud.example.com/remote.php/dav/calendars/username/
      username: !env NEXTCLOUD_USERNAME
      password: !env NEXTCLOUD_PASSWORD
      verify_ssl: true
      default_calendar_path: null
channels:
  default:
    type: telegram
    token: !env TELEGRAM_BOT_TOKEN
    stt: default
